version: '2'

services:
  redis:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6390:6379'

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    volumes:
      - ./bot:/data